name: release-npm-library
on:
  push:
    branches:
      - main
jobs:
  publish-npm:
    name: Publish package
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag-version.outputs.new_version }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run compile
      - run: npm run test
      - id: tag-version
        uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm version --no-git-tag-version -f ${{ steps.tag-version.outputs.new_version }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
